- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mlb-bot"
      - "--image=gcr.io/$PROJECT_ID/mlb-bot:$COMMIT_SHA"
      - "--region=us-east4"        # ← updated
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=512Mi"
      - "--timeout=120"
